#server:
#  port: 9527
#
#spring:
#  application:
#    name: cloud-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: paymentRoute               # 路由Id，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供服务胡路由地址
#          predicates:
#            - Path=/payment/get/**      #断言，路径匹配胡进行路由
#
#        - id: paymentRoute2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/feign/timeout/**
#
#
#
#eureka:
#  client:
#    register-with-eureka: true #表示是否向注册中心注册自己
#    fetch-registry: true #是否从eureka server抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/ # 不搭建集群 单机 指向自己
#  instance:
#    instance-id: gateway9527
#    prefer-ip-address: true #访问路径可以显示ip地址
#    lease-renewal-interval-in-seconds: 1 # eureka客户端向服务端发送心跳的时间间隔 单位秒 默认30
#    lease-expiration-duration-in-seconds: 2 # eureka
#



server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: paymentRoute               # 路由Id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001    #匹配后提供服务胡路由地址
          predicates:
            - Path=/payment/get/**      #断言，路径匹配胡进行路由

        - id: paymentRoute2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/feign/timeout/**

eureka:
  client:
    register-with-eureka: true #表示是否向注册中心注册自己
    fetch-registry: true #是否从eureka server抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/ # 不搭建集群 单机 指向自己
  instance:
    instance-id: gateway9527
    prefer-ip-address: true #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 1 # eureka客户端向服务端发送心跳的时间间隔 单位秒 默认30
    lease-expiration-duration-in-seconds: 2 # eureka

