server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索实例
    #service-url: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置eureka server的地址，查询服务和注册服务都需要以来这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ # 不搭建集群 单机 指向自己