server:
  port: 9008
spring:
  datasource:
    url: jdbc:mysql:///flowable?serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: honger1234
