server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 #配置Nacos地址
        server-addr: 172.16.150.205:3333 #配置Nacos集群的地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
